---

- name: timedatectl
  command: timedatectl set-ntp true

- name: update exportfs
  shell: exportfs -rav

- name: restart collectd
  ansible.builtin.service:
    name: collectd
    state: restarted
