---

- name: install mysql packages
  apt: 
    pkg: "{{item}}"
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"
  with_items:
     - mysql-server
     - python-mysqldb
  tags:
     - mysql

- name: Create openhab database
  mysql_db:
    name: openhab
    state: present
  tags:
     - mysql

- mysql_user:
    name: openhab
    password: openhab
    priv: '*.*:ALL'
    state: present
  tags:
     - mysql


