---

- name: ensure packages are installed
  apt: 
    pkg: "{{item}}"
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"
  with_items:
     - nfs-common
     - nfs-kernel-server
  tags:
     - packages
     - nfs
     - openhab

- name: update /etc/exports
  lineinfile:
    dest=/etc/exports
    regexp="^{{item.mount_point}}\s.*"
    line="{{item.mount_point}} {{item.options}}"
  notify: update exportfs
  with_items:
    - { mount_point: "/etc/openhab", options: "*(rw,sync,no_subtree_check,all_squash)" }
  tags:
    - nfs
    - nfsconfig
    - openhab



