---

- name: install mosquitto packages
  apt: 
    pkg:
    - mosquitto
    - mosquitto-clients
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"



