---

- name: install packages
  apt: 
    pkg:
    - python3-paho-mqtt
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"

- name: install mqttwarn
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pip:
    name: mqttwarn

- name: install config file
  template:
    src: mqttwarn.ini
    dest: "/etc/mqttwarn.ini"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: restart mqttwarn
  tags:
    - mqttwarnconfig

- name: create log dir
  file: 
    dest: "/var/log/mqttwarn"
    state: directory
    owner: pi
    group: pi

- name: install service file
  template:
    src: mqttwarn.service
    dest: "/etc/systemd/system/mqttwarn.service"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: restart mqttwarn

- name: "configure systemd"
  systemd:
    name: mqttwarn
    daemon_reload: yes
    enabled: true
    state: started 


