---

- name: install mysql packages
  apt: 
    pkg:
    - default-mysql-server
    - python-mysqldb
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"

- name: Create openhab database
  mysql_db:
    name: openhab2
    state: present
  tags:
     - mysql

- mysql_user:
    name: openhab2
    password: openhab2
    priv: '*.*:ALL'
    state: present


