---

- name: ensure packages are installed
  apt: 
    pkg:
    - nfs-common
    - nfs-kernel-server
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"

- name: update /etc/exports
  lineinfile:
    dest: "/etc/exports"
    regexp: '^{{item.mount_point}}\s.*'
    line: "{{item.mount_point}} {{item.options}}"
  notify: update exportfs
  with_items:
    - { mount_point: "/etc/openhab2", options: "*(rw,sync,no_subtree_check,all_squash)" }
    - { mount_point: "/var/lib/openhab2", options: "*(rw,sync,no_subtree_check,all_squash)" }



