---

- name:
  user: 
    name: openhab
    groups: "dialout"
    append: yes
  tags:
    - openhab2
    - user

- name: "configure systemd"
  systemd:
    name: openhab2
    daemon_reload: yes
    enabled: true
    state: started 
  tags:
    - openhab2

- name: Download Rollershutters dependencies
  get_url:
    url: "{{ item.src }}"
    dest: "/usr/share/openhab2/runtime/lib/boot/{{ item.name }}"
  loop:
    - { name: "jython-standalone-2.7.0.jar", src: "http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar" }
    - { name: "snakeyaml-1.18.jar", src: "http://central.maven.org/maven2/org/yaml/snakeyaml/1.18/snakeyaml-1.18.jar" }
  tags:
    - openhab2
    - jython


- name: cron job
  cron:
    name: "restart openhab"
    minute: "10"
    hour: "5"
    weekday: "0"
    job: 'systemctl restart nginx.service'
    cron_file: openhab
    user: root
  tags:
    - openhab2
    - openhab_cron

- name: cron job
  cron:
    name: "touch shutters"
    minute: "20"
    hour: "5"
    weekday: "0"
    job: 'touch /etc/openhab2/automation/jsr223/shutters.py'
    cron_file: openhab
    user: root
  tags:
    - openhab2
    - openhab_cron
