---

- name: install openhab packages
  apt: 
    pkg: "{{item}}"
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"
  with_items:
     - "{{jdk}}"
     - openhab2
     - openhab2-addons
     - openhab2-addons-legacy
     - sysstat
     - nginx
     - python-passlib
  tags:
     - packages
     - openhab2


