---

# http://docs.openhab.org/installation/linux.html#package-repository-installation

- name: install ppa key
  apt_key: 
    url: "https://bintray.com/user/downloadSubjectPublicKey?username=openhab"
    state: present
  tags:
     - repo
     - openhab2

- name: install openhab2 repo
  apt_repository:
    repo: 'deb https://dl.bintray.com/openhab/apt-repo2 stable main'
    #repo: 'deb http://openhab.jfrog.io/openhab/openhab-linuxpkg unstable main'
    state: present
    update_cache: yes
    filename: openhab2
  tags:
     - repo
     - openhab2

