---

# http://docs.openhab.org/installation/linux.html#package-repository-installation

- name: install ppa key
  apt_key: 
    url: "http://www.openhab.org/keys/public-key-snapshots.asc"
    state: present
  tags:
     - repo
     - openhab2

- name: install openhab2 repo
  apt_repository:
    repo: 'deb https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-offline/target/apt-repo/ /'
    state: present
    update_cache: yes
    filename: openhab2
  tags:
     - repo
     - openhab2

