---

- name: Adding user pi to group docker
  user: name=pi
        groups=docker
        append=yes

- name: install docker-compose file
  template:
    src: docker-compose.yaml
    dest: /home/pi/psa/docker-compose.yaml

- name: install patch
  copy:
    src: mylogger.py
    dest: /home/pi/psa/mylogger.py
