---

- name: ensure packages are installed
  apt: 
    pkg:
     - apt-transport-https
     - tmux
     - python3-pip
     - python3-requests
     - python3-websocket
     - ufw
     - docker-compose
     - python-docker
     - socat
     - tcpdump
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"


- name: set to iptables to legacy
  command: "update-alternatives --set iptables /usr/sbin/iptables-legacy"

- name: set to ip6tables to legacy
  command: "update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy"
