---

- name: ensure packages are installed
  apt: 
    pkg:
     - apt-transport-https
     - tmux
     - python3-pip
     - git
     - multitail
     - python3-requests
     - python3-websocket
    update_cache: "{{apt_config.update_cache}}"
    cache_valid_time: "{{apt_config.cache_valid_time}}"


