---

- name: alias
  copy:
     src: alias
     dest: "/home/pi/.alias"
     owner: pi
     group: pi
     mode: "u=rw,g=r,o=r"
  tags:
    - alias

- name: update bashrc
  lineinfile:
    dest=/home/pi/.bashrc
    line="test -s ~/.alias && . ~/.alias"
  tags:
    - alias

